# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/predator/Documents/Project/temp/libdiscid

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/predator/Documents/Project/temp/libdiscid

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# The main all target
all:
	@./src/normal.sh 1200 "libdiscid"
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test_core

# Build rule for target.
test_core: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_core
.PHONY : test_core

# fast build rule for target.
test_core/fast:
	$(MAKE) -f CMakeFiles/test_core.dir/build.make CMakeFiles/test_core.dir/build
.PHONY : test_core/fast

#=============================================================================
# Target rules for targets named discid

# Build rule for target.
discid: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 discid
.PHONY : discid

# fast build rule for target.
discid/fast:
	$(MAKE) -f CMakeFiles/discid.dir/build.make CMakeFiles/discid.dir/build
.PHONY : discid/fast

#=============================================================================
# Target rules for targets named test_read_full

# Build rule for target.
test_read_full: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_read_full
.PHONY : test_read_full

# fast build rule for target.
test_read_full/fast:
	$(MAKE) -f CMakeFiles/test_read_full.dir/build.make CMakeFiles/test_read_full.dir/build
.PHONY : test_read_full/fast

#=============================================================================
# Target rules for targets named libdiscid

# Build rule for target.
libdiscid: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libdiscid
.PHONY : libdiscid

# fast build rule for target.
libdiscid/fast:
	$(MAKE) -f CMakeFiles/libdiscid.dir/build.make CMakeFiles/libdiscid.dir/build
.PHONY : libdiscid/fast

#=============================================================================
# Target rules for targets named dist

# Build rule for target.
dist: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dist
.PHONY : dist

# fast build rule for target.
dist/fast:
	$(MAKE) -f CMakeFiles/dist.dir/build.make CMakeFiles/dist.dir/build
.PHONY : dist/fast

#=============================================================================
# Target rules for targets named test_put

# Build rule for target.
test_put: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_put
.PHONY : test_put

# fast build rule for target.
test_put/fast:
	$(MAKE) -f CMakeFiles/test_put.dir/build.make CMakeFiles/test_put.dir/build
.PHONY : test_put/fast

#=============================================================================
# Target rules for targets named discisrc

# Build rule for target.
discisrc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 discisrc
.PHONY : discisrc

# fast build rule for target.
discisrc/fast:
	$(MAKE) -f CMakeFiles/discisrc.dir/build.make CMakeFiles/discisrc.dir/build
.PHONY : discisrc/fast

#=============================================================================
# Target rules for targets named memcheck

# Build rule for target.
memcheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 memcheck
.PHONY : memcheck

# fast build rule for target.
memcheck/fast:
	$(MAKE) -f CMakeFiles/memcheck.dir/build.make CMakeFiles/memcheck.dir/build
.PHONY : memcheck/fast

#=============================================================================
# Target rules for targets named docs

# Build rule for target.
docs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 docs
.PHONY : docs

# fast build rule for target.
docs/fast:
	$(MAKE) -f CMakeFiles/docs.dir/build.make CMakeFiles/docs.dir/build
.PHONY : docs/fast

#=============================================================================
# Target rules for targets named test_read

# Build rule for target.
test_read: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_read
.PHONY : test_read

# fast build rule for target.
test_read/fast:
	$(MAKE) -f CMakeFiles/test_read.dir/build.make CMakeFiles/test_read.dir/build
.PHONY : test_read/fast

#=============================================================================
# Target rules for targets named check

# Build rule for target.
check: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check
.PHONY : check

# fast build rule for target.
check/fast:
	$(MAKE) -f CMakeFiles/check.dir/build.make CMakeFiles/check.dir/build
.PHONY : check/fast

examples/discid.o: examples/discid.c.o

.PHONY : examples/discid.o

# target to build an object file
examples/discid.c.o:
	$(MAKE) -f CMakeFiles/discid.dir/build.make CMakeFiles/discid.dir/examples/discid.c.o
.PHONY : examples/discid.c.o

examples/discid.i: examples/discid.c.i

.PHONY : examples/discid.i

# target to preprocess a source file
examples/discid.c.i:
	$(MAKE) -f CMakeFiles/discid.dir/build.make CMakeFiles/discid.dir/examples/discid.c.i
.PHONY : examples/discid.c.i

examples/discid.s: examples/discid.c.s

.PHONY : examples/discid.s

# target to generate assembly for a file
examples/discid.c.s:
	$(MAKE) -f CMakeFiles/discid.dir/build.make CMakeFiles/discid.dir/examples/discid.c.s
.PHONY : examples/discid.c.s

examples/discisrc.o: examples/discisrc.c.o

.PHONY : examples/discisrc.o

# target to build an object file
examples/discisrc.c.o:
	$(MAKE) -f CMakeFiles/discisrc.dir/build.make CMakeFiles/discisrc.dir/examples/discisrc.c.o
.PHONY : examples/discisrc.c.o

examples/discisrc.i: examples/discisrc.c.i

.PHONY : examples/discisrc.i

# target to preprocess a source file
examples/discisrc.c.i:
	$(MAKE) -f CMakeFiles/discisrc.dir/build.make CMakeFiles/discisrc.dir/examples/discisrc.c.i
.PHONY : examples/discisrc.c.i

examples/discisrc.s: examples/discisrc.c.s

.PHONY : examples/discisrc.s

# target to generate assembly for a file
examples/discisrc.c.s:
	$(MAKE) -f CMakeFiles/discisrc.dir/build.make CMakeFiles/discisrc.dir/examples/discisrc.c.s
.PHONY : examples/discisrc.c.s

src/base64.o: src/base64.c.o

.PHONY : src/base64.o

# target to build an object file
src/base64.c.o:
	$(MAKE) -f CMakeFiles/libdiscid.dir/build.make CMakeFiles/libdiscid.dir/src/base64.c.o
.PHONY : src/base64.c.o

src/base64.i: src/base64.c.i

.PHONY : src/base64.i

# target to preprocess a source file
src/base64.c.i:
	$(MAKE) -f CMakeFiles/libdiscid.dir/build.make CMakeFiles/libdiscid.dir/src/base64.c.i
.PHONY : src/base64.c.i

src/base64.s: src/base64.c.s

.PHONY : src/base64.s

# target to generate assembly for a file
src/base64.c.s:
	$(MAKE) -f CMakeFiles/libdiscid.dir/build.make CMakeFiles/libdiscid.dir/src/base64.c.s
.PHONY : src/base64.c.s

src/disc.o: src/disc.c.o

.PHONY : src/disc.o

# target to build an object file
src/disc.c.o:
	$(MAKE) -f CMakeFiles/libdiscid.dir/build.make CMakeFiles/libdiscid.dir/src/disc.c.o
.PHONY : src/disc.c.o

src/disc.i: src/disc.c.i

.PHONY : src/disc.i

# target to preprocess a source file
src/disc.c.i:
	$(MAKE) -f CMakeFiles/libdiscid.dir/build.make CMakeFiles/libdiscid.dir/src/disc.c.i
.PHONY : src/disc.c.i

src/disc.s: src/disc.c.s

.PHONY : src/disc.s

# target to generate assembly for a file
src/disc.c.s:
	$(MAKE) -f CMakeFiles/libdiscid.dir/build.make CMakeFiles/libdiscid.dir/src/disc.c.s
.PHONY : src/disc.c.s

src/disc_linux.o: src/disc_linux.c.o

.PHONY : src/disc_linux.o

# target to build an object file
src/disc_linux.c.o:
	$(MAKE) -f CMakeFiles/libdiscid.dir/build.make CMakeFiles/libdiscid.dir/src/disc_linux.c.o
.PHONY : src/disc_linux.c.o

src/disc_linux.i: src/disc_linux.c.i

.PHONY : src/disc_linux.i

# target to preprocess a source file
src/disc_linux.c.i:
	$(MAKE) -f CMakeFiles/libdiscid.dir/build.make CMakeFiles/libdiscid.dir/src/disc_linux.c.i
.PHONY : src/disc_linux.c.i

src/disc_linux.s: src/disc_linux.c.s

.PHONY : src/disc_linux.s

# target to generate assembly for a file
src/disc_linux.c.s:
	$(MAKE) -f CMakeFiles/libdiscid.dir/build.make CMakeFiles/libdiscid.dir/src/disc_linux.c.s
.PHONY : src/disc_linux.c.s

src/sha1.o: src/sha1.c.o

.PHONY : src/sha1.o

# target to build an object file
src/sha1.c.o:
	$(MAKE) -f CMakeFiles/libdiscid.dir/build.make CMakeFiles/libdiscid.dir/src/sha1.c.o
.PHONY : src/sha1.c.o

src/sha1.i: src/sha1.c.i

.PHONY : src/sha1.i

# target to preprocess a source file
src/sha1.c.i:
	$(MAKE) -f CMakeFiles/libdiscid.dir/build.make CMakeFiles/libdiscid.dir/src/sha1.c.i
.PHONY : src/sha1.c.i

src/sha1.s: src/sha1.c.s

.PHONY : src/sha1.s

# target to generate assembly for a file
src/sha1.c.s:
	$(MAKE) -f CMakeFiles/libdiscid.dir/build.make CMakeFiles/libdiscid.dir/src/sha1.c.s
.PHONY : src/sha1.c.s

src/toc.o: src/toc.c.o

.PHONY : src/toc.o

# target to build an object file
src/toc.c.o:
	$(MAKE) -f CMakeFiles/libdiscid.dir/build.make CMakeFiles/libdiscid.dir/src/toc.c.o
.PHONY : src/toc.c.o

src/toc.i: src/toc.c.i

.PHONY : src/toc.i

# target to preprocess a source file
src/toc.c.i:
	$(MAKE) -f CMakeFiles/libdiscid.dir/build.make CMakeFiles/libdiscid.dir/src/toc.c.i
.PHONY : src/toc.c.i

src/toc.s: src/toc.c.s

.PHONY : src/toc.s

# target to generate assembly for a file
src/toc.c.s:
	$(MAKE) -f CMakeFiles/libdiscid.dir/build.make CMakeFiles/libdiscid.dir/src/toc.c.s
.PHONY : src/toc.c.s

src/unix.o: src/unix.c.o

.PHONY : src/unix.o

# target to build an object file
src/unix.c.o:
	$(MAKE) -f CMakeFiles/libdiscid.dir/build.make CMakeFiles/libdiscid.dir/src/unix.c.o
.PHONY : src/unix.c.o

src/unix.i: src/unix.c.i

.PHONY : src/unix.i

# target to preprocess a source file
src/unix.c.i:
	$(MAKE) -f CMakeFiles/libdiscid.dir/build.make CMakeFiles/libdiscid.dir/src/unix.c.i
.PHONY : src/unix.c.i

src/unix.s: src/unix.c.s

.PHONY : src/unix.s

# target to generate assembly for a file
src/unix.c.s:
	$(MAKE) -f CMakeFiles/libdiscid.dir/build.make CMakeFiles/libdiscid.dir/src/unix.c.s
.PHONY : src/unix.c.s

test/test.o: test/test.c.o

.PHONY : test/test.o

# target to build an object file
test/test.c.o:
	$(MAKE) -f CMakeFiles/test_core.dir/build.make CMakeFiles/test_core.dir/test/test.c.o
	$(MAKE) -f CMakeFiles/test_read_full.dir/build.make CMakeFiles/test_read_full.dir/test/test.c.o
	$(MAKE) -f CMakeFiles/test_put.dir/build.make CMakeFiles/test_put.dir/test/test.c.o
	$(MAKE) -f CMakeFiles/test_read.dir/build.make CMakeFiles/test_read.dir/test/test.c.o
.PHONY : test/test.c.o

test/test.i: test/test.c.i

.PHONY : test/test.i

# target to preprocess a source file
test/test.c.i:
	$(MAKE) -f CMakeFiles/test_core.dir/build.make CMakeFiles/test_core.dir/test/test.c.i
	$(MAKE) -f CMakeFiles/test_read_full.dir/build.make CMakeFiles/test_read_full.dir/test/test.c.i
	$(MAKE) -f CMakeFiles/test_put.dir/build.make CMakeFiles/test_put.dir/test/test.c.i
	$(MAKE) -f CMakeFiles/test_read.dir/build.make CMakeFiles/test_read.dir/test/test.c.i
.PHONY : test/test.c.i

test/test.s: test/test.c.s

.PHONY : test/test.s

# target to generate assembly for a file
test/test.c.s:
	$(MAKE) -f CMakeFiles/test_core.dir/build.make CMakeFiles/test_core.dir/test/test.c.s
	$(MAKE) -f CMakeFiles/test_read_full.dir/build.make CMakeFiles/test_read_full.dir/test/test.c.s
	$(MAKE) -f CMakeFiles/test_put.dir/build.make CMakeFiles/test_put.dir/test/test.c.s
	$(MAKE) -f CMakeFiles/test_read.dir/build.make CMakeFiles/test_read.dir/test/test.c.s
.PHONY : test/test.c.s

test/test_core.o: test/test_core.c.o

.PHONY : test/test_core.o

# target to build an object file
test/test_core.c.o:
	$(MAKE) -f CMakeFiles/test_core.dir/build.make CMakeFiles/test_core.dir/test/test_core.c.o
.PHONY : test/test_core.c.o

test/test_core.i: test/test_core.c.i

.PHONY : test/test_core.i

# target to preprocess a source file
test/test_core.c.i:
	$(MAKE) -f CMakeFiles/test_core.dir/build.make CMakeFiles/test_core.dir/test/test_core.c.i
.PHONY : test/test_core.c.i

test/test_core.s: test/test_core.c.s

.PHONY : test/test_core.s

# target to generate assembly for a file
test/test_core.c.s:
	$(MAKE) -f CMakeFiles/test_core.dir/build.make CMakeFiles/test_core.dir/test/test_core.c.s
.PHONY : test/test_core.c.s

test/test_put.o: test/test_put.c.o

.PHONY : test/test_put.o

# target to build an object file
test/test_put.c.o:
	$(MAKE) -f CMakeFiles/test_put.dir/build.make CMakeFiles/test_put.dir/test/test_put.c.o
.PHONY : test/test_put.c.o

test/test_put.i: test/test_put.c.i

.PHONY : test/test_put.i

# target to preprocess a source file
test/test_put.c.i:
	$(MAKE) -f CMakeFiles/test_put.dir/build.make CMakeFiles/test_put.dir/test/test_put.c.i
.PHONY : test/test_put.c.i

test/test_put.s: test/test_put.c.s

.PHONY : test/test_put.s

# target to generate assembly for a file
test/test_put.c.s:
	$(MAKE) -f CMakeFiles/test_put.dir/build.make CMakeFiles/test_put.dir/test/test_put.c.s
.PHONY : test/test_put.c.s

test/test_read.o: test/test_read.c.o

.PHONY : test/test_read.o

# target to build an object file
test/test_read.c.o:
	$(MAKE) -f CMakeFiles/test_read.dir/build.make CMakeFiles/test_read.dir/test/test_read.c.o
.PHONY : test/test_read.c.o

test/test_read.i: test/test_read.c.i

.PHONY : test/test_read.i

# target to preprocess a source file
test/test_read.c.i:
	$(MAKE) -f CMakeFiles/test_read.dir/build.make CMakeFiles/test_read.dir/test/test_read.c.i
.PHONY : test/test_read.c.i

test/test_read.s: test/test_read.c.s

.PHONY : test/test_read.s

# target to generate assembly for a file
test/test_read.c.s:
	$(MAKE) -f CMakeFiles/test_read.dir/build.make CMakeFiles/test_read.dir/test/test_read.c.s
.PHONY : test/test_read.c.s

test/test_read_full.o: test/test_read_full.c.o

.PHONY : test/test_read_full.o

# target to build an object file
test/test_read_full.c.o:
	$(MAKE) -f CMakeFiles/test_read_full.dir/build.make CMakeFiles/test_read_full.dir/test/test_read_full.c.o
.PHONY : test/test_read_full.c.o

test/test_read_full.i: test/test_read_full.c.i

.PHONY : test/test_read_full.i

# target to preprocess a source file
test/test_read_full.c.i:
	$(MAKE) -f CMakeFiles/test_read_full.dir/build.make CMakeFiles/test_read_full.dir/test/test_read_full.c.i
.PHONY : test/test_read_full.c.i

test/test_read_full.s: test/test_read_full.c.s

.PHONY : test/test_read_full.s

# target to generate assembly for a file
test/test_read_full.c.s:
	$(MAKE) -f CMakeFiles/test_read_full.dir/build.make CMakeFiles/test_read_full.dir/test/test_read_full.c.s
.PHONY : test/test_read_full.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... list_install_components"
	@echo "... install/strip"
	@echo "... test_core"
	@echo "... discid"
	@echo "... test_read_full"
	@echo "... libdiscid"
	@echo "... install/local"
	@echo "... dist"
	@echo "... test_put"
	@echo "... discisrc"
	@echo "... memcheck"
	@echo "... docs"
	@echo "... test_read"
	@echo "... check"
	@echo "... examples/discid.o"
	@echo "... examples/discid.i"
	@echo "... examples/discid.s"
	@echo "... examples/discisrc.o"
	@echo "... examples/discisrc.i"
	@echo "... examples/discisrc.s"
	@echo "... src/base64.o"
	@echo "... src/base64.i"
	@echo "... src/base64.s"
	@echo "... src/disc.o"
	@echo "... src/disc.i"
	@echo "... src/disc.s"
	@echo "... src/disc_linux.o"
	@echo "... src/disc_linux.i"
	@echo "... src/disc_linux.s"
	@echo "... src/sha1.o"
	@echo "... src/sha1.i"
	@echo "... src/sha1.s"
	@echo "... src/toc.o"
	@echo "... src/toc.i"
	@echo "... src/toc.s"
	@echo "... src/unix.o"
	@echo "... src/unix.i"
	@echo "... src/unix.s"
	@echo "... test/test.o"
	@echo "... test/test.i"
	@echo "... test/test.s"
	@echo "... test/test_core.o"
	@echo "... test/test_core.i"
	@echo "... test/test_core.s"
	@echo "... test/test_put.o"
	@echo "... test/test_put.i"
	@echo "... test/test_put.s"
	@echo "... test/test_read.o"
	@echo "... test/test_read.i"
	@echo "... test/test_read.s"
	@echo "... test/test_read_full.o"
	@echo "... test/test_read_full.i"
	@echo "... test/test_read_full.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

